# #1 write a function to compute 5/0 and use try/except to catch the exception?
# try:
#     k = 5//0 
#     print(k)     
# except ZeroDivisionError:    
#     print("Can't divide by zero") 
        
# finally: 

#     print('This is always executed')  

